//! cordis-loader: configuration-driven assembly on top of cordis-core
//! (docs/04-services-events-loader.md §4, docs/06 P6–P7).
//!
//! The loader is deliberately split along one seam:
//!
//! - a **pure data path** — parse JSON layers, compose them into a tree
//!   with provenance, validate strictly, dump for humans. It loads no
//!   plugins, spawns no tasks and reads no environment
//!   (docs/04 §4.1);
//! - a **runtime path** — a registry of typed plugin constructors, mount
//!   (with predecode, groups and all-or-nothing failure recovery),
//!   unmount with awaited reports, and a pure reconcile plan whose
//!   application preserves unchanged fiber identities and binds one tree
//!   revision per apply.
//!
//! serde lives in this crate only; cordis-core stays dependency-free
//! besides Tokio. Numbers keep exact `u64`/`i64` values through the whole
//! pipeline; integer literals beyond that range are rejected loudly
//! instead of silently degrading through `f64` (docs/06 P6.2, V44).
//!
//! Golden fixtures under `tests/fixtures/` were generated by running the
//! `../cordis-go` loader (see `tests/golden.rs`); intentional differences
//! are listed there.
//!
//! ## Minimal usage
//!
//! The pure data path needs no runtime and loads nothing:
//!
//! ```
//! use cordis_loader::{ComposeOptions, DumpOptions, Layer, compose, dump};
//!
//! let base = Layer::parse(
//!     "base",
//!     r#"[{"id":"db","name":"db-plugin","config":{"url":"postgres://a","secret":"hunter2"}}]"#,
//! )
//! .expect("base layer parses");
//! // A patch overrides only the fields it mentions; `config` replaces
//! // the target config as a whole (never a deep merge).
//! let patch = Layer::parse_patch(
//!     "profile",
//!     r#"[{"id":"db","config":{"url":"postgres://b","secret":"hunter3"}}]"#,
//! )
//! .expect("patch layer parses");
//!
//! let tree = compose(&[base, patch], ComposeOptions::default()).expect("compose");
//! let node = tree.find("db").expect("node exists");
//! assert_eq!(node.source, "base");
//! assert_eq!(node.patched_by, vec!["profile".to_owned()]);
//! assert_eq!(
//!     node.config.as_ref().unwrap()["url"].as_str(),
//!     Some("postgres://b")
//! );
//!
//! // Dumps answer "what will load, and which layer decided that?" —
//! // with sensitive values masked by default.
//! let text = dump(&tree, DumpOptions::redacted());
//! assert!(text.contains("postgres://b"));
//! assert!(!text.contains("hunter3"));
//! ```
//!
//! The runtime path mounts a composed tree onto a [`cordis_core::App`];
//! see the workspace-level `examples/loader.rs` for an end-to-end run
//! including a reconcile pass.

#![forbid(unsafe_code)]

mod compose;
mod dump;
mod error;
mod model;
mod mount;
mod plan;
mod registry;

pub use compose::{ComposeOptions, compose};
pub use dump::{DumpOptions, dump};
pub use error::{LoaderError, Result};
pub use model::{Layer, Node, NodeId, Patch, Tree};
pub use mount::{MountReport, MountedEntry, MountedTree, mount, predecode, unmount};
pub use plan::{Action, PlanEntry, ReconcilePlan, ReconcileReport, plan, plan_report, reconcile};
pub use registry::Registry;

/// Re-exported so registration closures can name the JSON value type
/// without depending on serde_json directly.
pub use serde_json::Value as JsonValue;

#[cfg(test)]
mod tests {
    /// The two crates must keep linking with compatible metadata.
    #[test]
    fn loader_links_against_core() {
        assert_eq!(cordis_core::SCAFFOLD_VERSION, "0.1.0");
    }
}
